on:
  push:
    branches:
    - main

permissions:
  contents: read

name: main
jobs:
  build:
    name: Build MagickViewer
    runs-on: windows-2022

    permissions:
      id-token: write

    outputs:
      has-tag: ${{ steps.check-tag.outputs.has-tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-tags: true
          persist-credentials: false

      - name: Check if commit has tag
        if: github.event_name != 'pull_request'
        id: check-tag
        shell: powershell
        run: |
          $tag = git tag --points-at HEAD
          if ($tag) {
            echo "Tag found: $tag"
            echo "has-tag=true" >> $env:GITHUB_OUTPUT
          } else {
            echo "No tag found"
            echo "has-tag=false" >> $env:GITHUB_OUTPUT
          }

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore MagickViewer/packages.config -PackagesDirectory packages

      - name: Build
        run: msbuild MagickViewer.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Publish
        run: msbuild MagickViewer.sln /p:Configuration=Release /p:Platform="Any CPU" /p:PublishClickOnce=true /t:PublishClickOnce

      - name: Sign executables and libraries
        uses: ImageMagick/code-signing-action@4d19869732e1cd97bb823ad21ebffb26ad10836c # v1.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          directory: ${{ github.workspace }}\MagickViewer\bin\Release\app.publish
          files: 'MagickViewer.application'

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
        with:
          name: MagickViewer
          path: MagickViewer\bin\Release\app.publish\**

  deploy:
    name: Deploy MagickViewer
    runs-on: windows-2022
    needs: build
    if: needs.build.outputs.has-tag == 'true'
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 #v7.0.0
        with:
          name: MagickViewer
          path: MagickViewer

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@657f0700ea5214d56a0400d8ac5e8023c963d25d #3.0.6
        with:
          app-name: magickviewer
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: MagickViewer